// Playground constants
export const PARSE_TEST_PATTERN = "PARSE_TEST_PATTERN";
export const TEST_PATTERN_CHANGE = "TEST_PATTERN_CHANGE";
export const COPY_TEST_LIST_TO_CLIPBOARD = "COPY_TEST_LIST_TO_CLIPBOARD";
export const EMPTY_TEST_LIST = "EMPTY_TEST_LIST";
